/*
 * Copyright (c) 2025-2030 Beilstein-Institut
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
package org.beilstein.chemxtract.converter;

import java.util.HashMap;
import java.util.Map;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.beilstein.chemxtract.cdx.CDAtom;
import org.beilstein.chemxtract.cdx.CDBond;
import org.beilstein.chemxtract.cdx.datatypes.CDBondCIPType;
import org.beilstein.chemxtract.cdx.datatypes.CDBondDisplay;
import org.beilstein.chemxtract.cdx.datatypes.CDBondOrder;
import org.openscience.cdk.CDKConstants;
import org.openscience.cdk.exception.CDKException;
import org.openscience.cdk.interfaces.IAtom;
import org.openscience.cdk.interfaces.IBond;
import org.openscience.cdk.interfaces.IChemObjectBuilder;
import org.openscience.cdk.isomorphism.matchers.Expr;
import org.openscience.cdk.isomorphism.matchers.QueryBond;

/**
 * Converts {@link CDBond} instances (e.g. from ChemDraw/CDXML or CDX) into CDK {@link IBond}
 * objects.
 *
 * <p>The {@code BondConverter} class translates ChemDraw bond specifications, including bond order,
 * display style, and stereochemistry, into their corresponding CDK representations. It also
 * supports query bonds such as "single or double" and "single or aromatic" to enable substructure
 * matching and uncertain connectivity representations.
 *
 * <p>The converter relies on an externally provided atom mapping from {@link CDAtom} to {@link
 * IAtom}, typically generated by {@link AtomConverter}. This ensures that bonds connect the correct
 * CDK atom instances corresponding to the ChemDraw atoms.
 *
 * <p><b>Usage example:</b>
 *
 * <pre>{@code
 * IChemObjectBuilder builder = DefaultChemObjectBuilder.getInstance();
 * Map<CDAtom, IAtom> atomMap = atomConverter.getAtomMap();
 * BondConverter bondConverter = new BondConverter(builder, atomMap);
 * IBond bond = bondConverter.convert(cdBond);
 * }</pre>
 */
public class BondConverter {

  private final IChemObjectBuilder builder;
  private static final Log logger = LogFactory.getLog(BondConverter.class);
  private final Map<CDAtom, IAtom> atomMap;
  private final Map<CDBond, IBond> bondMap;

  /**
   * Constructs a new {@code BondConverter} using the given {@link IChemObjectBuilder} and atom
   * mapping.
   *
   * @param builder the CDK {@link IChemObjectBuilder} used to instantiate bonds
   * @param atomMap a mapping from {@link CDAtom} to their converted {@link IAtom} counterparts,
   *     created by {@link AtomConverter}
   */
  public BondConverter(IChemObjectBuilder builder, Map<CDAtom, IAtom> atomMap) {
    this.builder = builder;
    this.atomMap = atomMap;
    this.bondMap = new HashMap<>();
  }

  /**
   * Converts a {@link CDBond} into a CDK {@link IBond}.
   *
   * <p>The method creates a new bond between the corresponding CDK atoms, assigns bond order,
   * aromaticity, and stereochemistry, and stores the result in an internal bond map.
   *
   * @param source the {@link CDBond} object to convert
   * @return the created {@link IBond} instance
   * @throws CDKException if an unsupported or invalid bond order is encountered
   */
  public IBond convert(CDBond source) throws CDKException {
    IAtom atom1 = atomMap.get(source.getBegin());
    IAtom atom2 = atomMap.get(source.getEnd());

    IBond bond = builder.newBond();
    bond.setAtoms(new IAtom[] {atom1, atom2});

    // set bond order
    CDBondOrder cdOrder = source.getBondOrder();
    switch (cdOrder) {
      case Single:
        bond.setOrder(IBond.Order.SINGLE);
        break;
      case Double:
        bond.setOrder(IBond.Order.DOUBLE);
        break;
      case Triple:
        bond.setOrder(IBond.Order.TRIPLE);
        break;
      case OneHalf: // aromatic
        bond.setOrder(IBond.Order.SINGLE);
        bond.setIsAromatic(true);
        bond.setFlag(CDKConstants.SINGLE_OR_DOUBLE, true);
        bond.getBegin().setIsAromatic(true);
        bond.getEnd().setIsAromatic(true);
        break;
      case SingleOrDouble:
        bond = new QueryBond(bond.getBegin(), bond.getEnd(), Expr.Type.SINGLE_OR_DOUBLE);
        break;
      case SingleOrAromatic:
        bond = new QueryBond(bond.getBegin(), bond.getEnd(), Expr.Type.SINGLE_OR_AROMATIC);
        break;
      case DoubleOrAromatic:
        bond = new QueryBond(bond.getBegin(), bond.getEnd(), Expr.Type.DOUBLE_OR_AROMATIC);
        break;
      case Any:
        bond = new QueryBond(bond.getBegin(), bond.getEnd(), Expr.Type.TRUE);
        break;
      default:
        throw new CDKException("Unsupported bond type: " + cdOrder.name());
    }
    // set single bond display type
    if (IBond.Order.SINGLE.equals(bond.getOrder())) {
      bond.setDisplay(convertSingleBondDisplay(source.getBondDisplay()));
    }
    // set double bond stereo
    else if (IBond.Order.DOUBLE.equals(bond.getOrder())) {
      bond.setStereo(convertDoubleBondStereo(source.getStereochemistry()));
    }
    bondMap.putIfAbsent(source, bond);
    return bond;
  }

  /**
   * Converts a ChemDraw single bond display type into the corresponding CDK {@link IBond.Display}
   * enumeration.
   *
   * <p>
   *
   * @param cdBondDisplay the ChemDraw bond display type
   * @return the corresponding {@link IBond.Display} value
   */
  private IBond.Display convertSingleBondDisplay(CDBondDisplay cdBondDisplay) {
    if (cdBondDisplay == null) {
      return IBond.Display.Solid;
    }
    return switch (cdBondDisplay) {
      case WedgeBegin -> IBond.Display.WedgeBegin;
      case WedgedHashBegin -> IBond.Display.WedgedHashBegin;
      case WedgeEnd -> IBond.Display.WedgeEnd;
      case WedgedHashEnd -> IBond.Display.WedgedHashEnd;
      case Bold -> IBond.Display.Bold;
      case Hash -> IBond.Display.Hash;
      case Wavy -> IBond.Display.Wavy;
      case Dash -> IBond.Display.Dash;
      default -> IBond.Display.Solid;
    };
  }

  /**
   * Converts a ChemDraw-defined double bond stereochemistry (E/Z/Undetermined) into the
   * corresponding CDK {@link IBond.Stereo} value.
   *
   * <p>Returns {@link IBond.Stereo#NONE} if the stereochemistry is null or unrecognized.
   *
   * @param stereo the ChemDraw CIP-type stereo designation
   * @return the corresponding {@link IBond.Stereo} value
   */
  private IBond.Stereo convertDoubleBondStereo(CDBondCIPType stereo) {
    if (stereo == null) {
      return IBond.Stereo.NONE;
    }
    switch (stereo) {
      case E -> {
        return IBond.Stereo.E;
      }
      case Z -> {
        return IBond.Stereo.Z;
      }
      case Undetermined -> {
        return IBond.Stereo.E_OR_Z;
      }
      default -> {
        return IBond.Stereo.NONE;
      }
    }
  }

  /**
   * Returns the internal mapping between source {@link CDBond} and generated {@link IBond}.
   *
   * @return an unmodifiable view of the bond map
   */
  public Map<CDBond, IBond> getBondMap() {
    return bondMap;
  }
}
